networks:
  appnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  # API im gleichen Netz wie DB + auf Start der gesunden DB warten
  api:
    restart: unless-stopped
    networks:
      appnet:
        ipv4_address: 172.28.0.10
    depends_on:
      db:
        condition: service_healthy
        required: true

  # Caddy bleibt auf appnet
  caddy:
    networks:
      appnet:
        ipv4_address: 172.28.0.11

  # DB jetzt ebenfalls auf appnet + Healthcheck
  db:
    networks:
      appnet:
        ipv4_address: 172.28.0.12
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1 -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 5s
